apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-frontend
spec:
  selector:
    matchLabels:
      app: custom-frontend
      tier: frontend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: custom-frontend
        tier: frontend
        track: stable
    spec:
      containers:
        - name: hello
          image: mprambadi/hello-vue
          ports:
            - name: http
              containerPort: 80